fix: set maximal attempts for ask for sast feature
snyk/snyk-intellij-plugin pull request #123
Opened 2021-06-09 20:04 UTC by pavel-snyk

This PR fix the issue with infinite loop to ask API for enabling/disabling SAST feature. Maximal attempt count is 20.

2021-06-09 22:41 UTC, davidleger95 approved these changes

2021-06-10 06:24 UTC, michelkaporin approved these changes

2021-06-10 08:39 UTC, ArtsiomCh requested changes
That will lead to the same problem we have with Auth: https://snyksec.atlassian.net/browse/ROAD-19?atlOrigin=eyJpIjoiNWViNTUxMmRmMDE0NDVjZjg2Mjk0NzJkZmQzMWRkYTciLCJwIjoiaiJ9
I.e. hardcoding the specific number of attempts (timeframe) will cuase to brake the flow for the "slow" users.
Also don't think we really need that as far as the loop is not infinite, it will be stopped and disposed when `parentDisposable` (parent Settings/Onboarding Panel) is disposed.

2021-06-10 09:08 UTC, ArtsiomCh approved these changes

2021-06-10 09:11 UTC, ArtsiomCh commented
Accept as workaround for now, but need to be reviewed later.
I see now the problem for which this fix is coming. Would be nice if we have ticket with context created before and then linked to this PR.

2021-06-10 09:39 UTC, merged