chore: 💄 rename plugin to `Snyk` [ROAD-654]
snyk/snyk-intellij-plugin pull request #321
Opened 2022-02-23 11:14 UTC by bastiandoetsch

![image](https://user-images.githubusercontent.com/20150761/155308703-55627597-20fb-4fc5-9e26-fb1c1fcf07b7.png)

2022-02-23 11:23 UTC, ArtsiomCh submitted a review, later dismissed

2022-02-28 15:17 UTC, deepcodeg requested changes
@pavel-snyk could we please sync the copy with the version 2's copy?

2022-02-28 16:03 UTC, pavel-snyk commented
@deepcodeg, sure.
The screenshot how it look inside of IDE is attached.

2022-02-28 20:35 UTC, ArtsiomCh approved these changes
Despite I'm still against that new name, I'll approve that PR as it's technically correct.

2022-02-28 22:23 UTC, merged