split cache update per product [ROAD753]
snyk/snyk-intellij-plugin pull request #331
Opened 2022-03-12 20:26 UTC by ArtsiomCh

2022-03-14 09:12 UTC, bastiandoetsch commented
Is there any actual code change or just splitting up, @ArtsiomCh?

2022-03-14 10:09 UTC, ArtsiomCh commented
@bastiandoetsch Just splitting Listeners to not affect each other in case of any fail.
Plus tests splitting/refactoring/addition (see commits titles)

2022-03-14 15:28 UTC, bastiandoetsch approved these changes

2022-03-14 16:54 UTC, bastiandoetsch requested changes
Please update changelog

2022-03-15 18:14 UTC, bastiandoetsch approved these changes

2022-03-16 09:35 UTC, merged