chore: enable request logging when SnykCode logger is in debug mode [ROAD-843]
snyk/snyk-intellij-plugin pull request #355
Opened 2022-04-08 16:47 UTC by bastiandoetsch

### Description

This PR enables HTTP request logging for the Snyk Code Client when the `SnykCode` logger is set to debug and enables to monitor / check API communication, thus.

### Checklist

- [ x ] Tests all succeed
- [ x ] Linted
- [ x ] CHANGELOG.md updated
- [ x ] README.md updated, if user-facing

### Screenshots / GIFs

2022-04-09 10:22 UTC, ArtsiomCh requested changes
Would be happy and not create the ticket if fix could be such an easy thing to do... :)

- We re-create `retrofit` from few other places, so that `requestLogin` param will be overridden to the default `false` there. See `ai.deepcode.javaclient.core.DeepCodeParamsBase#setApiUrl()` usages.
- Not sure where `HttpLoggingInterceptor` will output. Most likely to STDOUT and that probably(?) will go to Idea log as well, but need to be checked. 
- Don't think we want to see such a detailed logs (at least I see in failed tests it's very verbose) every time we have DEBUG level enabled for the snyk classes. Would prefer to have separate feature flag in Idea's Registry for that.
- also probably some tests need to be added...

2022-04-11 08:17 UTC, bastiandoetsch commented
moving to slack...

2022-04-20 09:35 UTC, ArtsiomCh requested changes
Some (easy) changes needed
Also please rebase CHANGELOG to resolve merge conflict

2022-04-20 09:35 UTC, ArtsiomCh commented on .snyk
> +    - src/integTest/*:
do we really want to ignore any vulns in our tests? may be just in resources...

2022-04-20 09:35 UTC, ArtsiomCh commented on .snyk
> +    - src/test/*:
see above

2022-04-20 09:35 UTC, ArtsiomCh commented on src/main/kotlin/io/snyk/plugin/snykcode/core/SnykCodeParams.kt
> +    private val requestLogging = Logger.getInstance(SCLogger.presentableName + "RequestLogging").isDebugEnabled
that should be `fun()` (or val with `get()`) cause we need to re-read setting every time it's called out (user can change it after class created).

2022-04-20 12:12 UTC, ArtsiomCh approved these changes
LGTM
Good job!

2022-04-20 12:20 UTC, merged